# Generated by Django 4.1.2 on 2022-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancemusic',
            name='id',
        ),
        migrations.AlterField(
            model_name='dancemusic',
            name='music_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
